Repository TheSuperHackers/GeneralsGameCode, pull requests merged in 2025-06, with the labels that each got.

#970 [GEN][ZH] Implement default key mapping for TOGGLE_FAST_FORWARD_REPLAY
  Generals/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/MetaEvent.cpp
Labels: Enhancement, Minor, Gen, ZH

#595 [GEN][ZH] Add Windows application manifest to executables
  Generals/Code/Main/CMakeLists.txt
  Generals/Code/Main/RTS.RC
  Generals/Code/Main/app.manifest
  GeneralsMD/Code/Main/CMakeLists.txt
  GeneralsMD/Code/Main/RTS.RC
  GeneralsMD/Code/Main/app.manifest
Labels: Enhancement, Minor, Build, Gen, ZH

#971 [GEN][ZH] Fix crash when exiting Replay playback while a player places a beacon
  Generals/Code/GameEngine/Include/Common/Recorder.h
  Generals/Code/GameEngine/Source/Common/Recorder.cpp
  GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
  GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
Labels: Bug, Minor, Gen, ZH, Crash

#989 [GEN][ZH] Fix logical errors with RecorderClass::testVersionPlayback()
  Generals/Code/GameEngine/Include/Common/Recorder.h
  Generals/Code/GameEngine/Source/Common/Recorder.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
  GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
Labels: Minor, Gen, ZH, Refactor, Fix

#406 [GEN][ZH] Improve Network logging
  Generals/Code/GameEngine/Include/GameNetwork/NetworkDefs.h
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/NetworkDirectConnect.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
  Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
  Generals/Code/GameEngine/Source/GameNetwork/FirewallHelper.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameSpyGameInfo.cpp
  Generals/Code/GameEngine/Source/GameNetwork/LANAPI.cpp
  Generals/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp
  Generals/Code/GameEngine/Source/GameNetwork/NAT.cpp
  Generals/Code/GameEngine/Source/GameNetwork/Transport.cpp
  GeneralsMD/Code/GameEngine/Include/GameNetwork/NetworkDefs.h
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/NetworkDirectConnect.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/FirewallHelper.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpyGameInfo.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPI.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/NAT.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/Transport.cpp
Labels: Network, ZH, Refactor, Debug

#976 [GEN][ZH] Decouple the Game Logic update in ParticleUplinkCannonUpdate from the Orbit To Ground Laser drawable
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp
Labels: Minor, Gen, ZH, Refactor

#1009 [CORE] Remove naked function declaration for WWMath::Inv_Sqrt
  Core/Libraries/Source/WWVegas/WWMath/wwmath.h
Labels: Minor, Refactor

#1001 [GEN][ZH] Fix crash on GameEngine shutdown when GameLogic::clearGameData() was not called before
  Generals/Code/GameEngine/Source/Common/GameEngine.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
Labels: Major, Gen, ZH, Debug, Crash

#1015 [GEN][ZH] Remove unnecessary try catch block in ~PlayerList()
  Generals/Code/GameEngine/Source/Common/RTS/PlayerList.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RTS/PlayerList.cpp
Labels: Minor, Refactor

#993 [GEN][ZH] Prevent game crash when starting a new game without a map
  Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
Labels: Minor, Gen, ZH, Stability, Crash

#992 [GEN][ZH] Implement REPLAY NOT FOUND and MAP NOT FOUND dialogs when attempting to load a Replay that was deleted or whose map is missing
  Core/GameEngine/Include/Common/GameDefines.h
  Generals/Code/GameEngine/Include/GameClient/GameText.h
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GameText.cpp
  GeneralsMD/Code/GameEngine/Include/GameClient/GameText.h
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp
Labels: Bug, Critical, Gen, ZH, Refactor, Crash

#1002 [CORE] Fix up RefCountClass, RefCountPtr<T>
  Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h
  Core/Libraries/Source/WWVegas/WWLib/refcount.h
  Generals/Code/GameEngine/Source/Common/StateMachine.cpp
  GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp
Labels: Minor, Refactor

#1013 [CORE] Cleanup wwmath header for consistency
  Core/Libraries/Source/WWVegas/WWMath/wwmath.h
Labels: Minor, Refactor

#1006 [ZH] Fix crash in TunnelContain::killAllContained() when killed occupants kill the host container
  GeneralsMD/Code/GameEngine/Include/Common/TunnelTracker.h
  GeneralsMD/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
Labels: Bug, Critical, ZH, Crash

#756 [GEN][ZH] Fix hollow BOX particles treated as LINE particles in ParticleSystem::computeParticlePosition()
  Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp
Labels: Minor, Fix

#515 Update README.md
  README.md
Labels: Documentation

#1044 [GEN][ZH] Fix logical expressions for TheGlobalData in TerrainTex and W3DShaderManager
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/TerrainTex.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
Labels: Minor, Gen, ZH, Fix

#1043 [GEN][ZH] Initialize all uninitialized variables in AIPathfind
  Generals/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPathfind.cpp
Labels: Major, Gen, ZH, Fix, Stability

#1052 [GEN][ZH] Add message with additional information on CRC mismatch in Replay playback
  Generals/Code/GameEngine/Source/Common/Recorder.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
Labels: Minor, Text, Debug

#1053 [GEN][ZH] Fix Clang, GCC compile errors from static enum declarations
  Generals/Code/GameEngine/Source/GameClient/MessageStream/GUICommandTranslator.cpp
  Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/BuddyThread.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/PeerThread.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/GUICommandTranslator.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/BuddyThread.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameSpy/Thread/PeerThread.cpp
Labels: Minor, CompileBug, Gen, ZH

#1003 [GEN][ZH] Fix static initialization order for StatDumpClass and LogClass
  Generals/Code/GameEngine/Source/Common/Dict.cpp
  Generals/Code/GameEngine/Source/Common/MiniLog.cpp
  Generals/Code/GameEngine/Source/Common/System/AsciiString.cpp
  Generals/Code/GameEngine/Source/Common/System/UnicodeString.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp
  GeneralsMD/Code/GameEngine/Source/Common/MiniLog.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/AsciiString.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/UnicodeString.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DModelDraw.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Labels: Minor, Fix, Stability

#1057 [CORE] Change memory order for std::atomic_flag::test_and_set in FastCriticalSectionClass and ProfileFastCS
  Core/Libraries/Source/WWVegas/WWLib/mutex.h
  Core/Libraries/Source/profile/internal.h
Labels: Minor, Fix

#1062 [GEN][ZH] Refactor non-trivial string objects as variadic function parameter
  Core/Libraries/Source/WWVegas/WW3D2/seglinerenderer.cpp
  Core/Libraries/Source/WWVegas/WWDebug/wwprofile.cpp
  Core/Libraries/Source/WWVegas/WWLib/cpudetect.cpp
  Core/Libraries/Source/WWVegas/WWLib/ffactory.cpp
  Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GameFont.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
  Generals/Code/GameEngine/Source/GameClient/MapUtil.cpp
  Generals/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
  Generals/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeBehavior.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Create/GrantUpgradeCreate.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp
  Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManager.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8renderer.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
  Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/texture.h
  Generals/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameFont.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/HeaderTemplate.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MapUtil.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeBehavior.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Create/GrantUpgradeCreate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/RailroadGuideAIUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
  GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DAssetManager.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ddsfile.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8caps.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.h
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/texturethumbnail.cpp
Labels: Minor, Refactor

#1071 [GEN][ZH] Fix clang compile errors with enums FilterTypes, FilterModes, BodyDamageType
  Generals/Code/GameEngine/Include/GameClient/View.h
  Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
  Generals/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
  Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
  Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DBridgeBuffer.h
  Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DShaderManager.h
  Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
  GeneralsMD/Code/GameEngine/Include/GameClient/View.h
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Map/TerrainLogic.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
  GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DBridgeBuffer.h
  GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DShaderManager.h
  GeneralsMD/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DBridgeBuffer.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp
Labels: Minor, CompileBug, Fix

#1051 [ZH] Set correct fake CRC for Zero Hour CD 1.04
  Generals/Code/GameEngine/Source/Common/GlobalData.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
Labels: Major, Network, ZH

#1016 [GEN][ZH] Simplify RecorderClass::appendNextCommand()
  Generals/Code/GameEngine/Source/Common/Recorder.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
Labels: Minor, Refactor

#1069 [GEN][ZH] Remove unnecessary 3 seconds delay from game startup
  Generals/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
Labels: Minor, Performance, Gen, ZH

#1070 [GEN][ZH] Fix some RTS_DEBUG and RTS_INTERNAL defines
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
  Generals/Code/GameEngine/Source/GameNetwork/Connection.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanGameOptionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/LanLobbyMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/Connection.cpp
Labels: Build, Fix

#1078 [GEN][ZH] Change reference counter implementation for StateMachine to avoid mismatch with Retail
  Core/Libraries/Source/WWVegas/WWLib/refcount.h
  Generals/Code/GameEngine/Include/Common/StateMachine.h
  GeneralsMD/Code/GameEngine/Include/Common/StateMachine.h
Labels: Major, Gen, ZH, Fix, Stability

#1007 [GEN][ZH] Refactor evacuation code in OpenContain, TunnelContain
  Generals/Code/GameEngine/Include/Common/TunnelTracker.h
  Generals/Code/GameEngine/Source/Common/RTS/TunnelTracker.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp
Labels: Minor, Gen, ZH, Refactor

#1060 [GEN][ZH] Prevent IP options from changing when changing the Display Resolution in the Options Menu
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp
Labels: Bug, Critical, GUI, Gen, ZH

#1058 [GEN][ZH] Fix security issue in map transfer by validating file paths when creating real paths from portable paths
  Generals/Code/GameEngine/Include/Common/FileSystem.h
  Generals/Code/GameEngine/Include/Common/LocalFileSystem.h
  Generals/Code/GameEngine/Source/Common/System/FileSystem.cpp
  Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
  Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
  Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32LocalFileSystem.h
  Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp
  GeneralsMD/Code/GameEngine/Include/Common/FileSystem.h
  GeneralsMD/Code/GameEngine/Include/Common/LocalFileSystem.h
  GeneralsMD/Code/GameEngine/Source/Common/System/FileSystem.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
  GeneralsMD/Code/GameEngineDevice/Include/StdDevice/Common/StdLocalFileSystem.h
  GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32LocalFileSystem.h
  GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp
  GeneralsMD/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp
Labels: Bug, Critical, Gen, ZH, Security

#1039 [CORE][GEN][ZH] Make tools compile with clang-cl in VS2022
  Core/Tools/ImagePacker/Source/WindowProcedures/PreviewProc.cpp
  Core/Tools/W3DView/BoneMgrDialog.cpp
  Core/Tools/W3DView/HierarchyPropPage.cpp
  Core/Tools/W3DView/MainFrm.cpp
  Core/Tools/W3DView/MeshPropPage.cpp
  Generals/Code/Tools/ParticleEditor/CColorAlphaDialog.cpp
  Generals/Code/Tools/WorldBuilder/include/wbview3d.h
  Generals/Code/Tools/WorldBuilder/src/DrawObject.cpp
  Generals/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
  GeneralsMD/Code/Tools/ParticleEditor/CColorAlphaDialog.cpp
  GeneralsMD/Code/Tools/WorldBuilder/include/wbview3d.h
  GeneralsMD/Code/Tools/WorldBuilder/src/DrawObject.cpp
  GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
  GeneralsMD/Code/Tools/wdump/chunk_d.cpp
Labels: Minor, CompileBug, Build, Tools

#1104 [CORE] Fix compile error "friend cannot be used with static" in mangler's and matchbot's threadfac.h
  Core/Tools/mangler/wlib/threadfac.h
  Core/Tools/matchbot/wlib/threadfac.h
Labels: Major, CompileBug, Build, Tools

#1115 [GITHUB] Disable VCPKG builds and remove INTERNAL builds to speed up CI
  .github/workflows/ci.yml
Labels: Critical, Performance, Build

#1108 [CORE] Prevent dereferencing NULL pointer 't' in Record_Texture_End()
  Core/Libraries/Source/WWVegas/WW3D2/statistics.cpp
Labels: Minor, Debug, Fix

#1118 [GEN][ZH] Replace TheGlobalData macro with inline variable to make debugging easier
  Generals/Code/GameEngine/Include/Common/GlobalData.h
  GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
Labels: Minor, Refactor, Debug

#1128 [GEN][ZH] Downgrade debug assertion to log for isPathInDirectory
  Generals/Code/GameEngine/Source/Common/System/FileSystem.cpp
  Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/FileSystem.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp
Labels: Minor, Refactor, Debug

#1098 [ZH] Fix heap-use-after-free in LayersList::updateUIFromList() when creating a new map in World Builder
  GeneralsMD/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
Labels: Major, WorldBuilder, ZH, Fix

#1099 [GEN] Backport bug fixes in CWorldBuilderDoc::OnNewDocument from Zero Hour
  Generals/Code/Tools/WorldBuilder/src/WorldBuilderDoc.cpp
Labels: Bug, Major, WorldBuilder, Gen, Unify

#1085 [GEN][ZH] Annotate fallthrough between various switch case labels
  Core/Libraries/Source/WWVegas/WWLib/always.h
  Dependencies/Utility/Utility/CppMacros.h
  Generals/Code/GameEngine/Source/Common/RandomValue.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
  Generals/Code/GameEngine/Source/GameClient/GameText.cpp
  Generals/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
  Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RandomValue.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowTransitionsStyles.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/WindowXlat.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/HackInternetAIUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/JetAIUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/MissileAIUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/SpecialAbilityUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/Scripts.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/meshmdlio.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
Labels: Minor, Refactor

#1086 [GEN][ZH] Prevent using uninitialized memory 'offset_u' in W3DTankDraw, W3DTankTruckDraw
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp
Labels: Minor, Fix

#1088 [GEN][ZH] Prevent using uninitialized memory 'start', 'end' in BridgeScaffoldBehavior::update()
  Generals/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/BridgeScaffoldBehavior.cpp
Labels: Minor, Refactor

#1089 [GEN][ZH] Prevent dereferencing NULL pointer 'tex' in WW3DAssetManager::Get_Texture()
  Generals/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/assetmgr.cpp
Labels: Minor, Fix

#1090 [GEN][ZH] Prevent reading invalid data in LoadScreen
  Generals/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/LoadScreen.cpp
Labels: Minor, Fix

#1094 [GEN][ZH] Fix using uninitialized memory 'curVictim' in EMPUpdate
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/EMPUpdate.cpp
Labels: Minor, Fix, Mod

#1096 [GEN][ZH] Prevent dereferencing NULL pointer 'TheAI' in AI::parseAiDataDefinition()
  Generals/Code/GameEngine/Source/GameLogic/AI/AI.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AI.cpp
Labels: Minor, Refactor

#1101 [GEN][ZH] Prevent dereferencing NULL pointer 'that' in PhysicsBehavior::transferVelocityTo()
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
Labels: Minor, Fix

#1103 [GEN][ZH] Fix heap-use-after-free in DisconnectManager::update()
  Generals/Code/GameEngine/Source/GameNetwork/DisconnectManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/DisconnectManager.cpp
Labels: Bug, Major, Memory, Stability

#1111 [GEN][ZH] Prevent buffer overrun while writing to 'new_types', 'new_lensflares' in DazzleRenderObjClass
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dazzle.cpp
Labels: Minor, Fix

#1112 [GEN][ZH] Fix dereferencing NULL pointer 'ext' in DX8Wrapper::_Create_DX8_Surface()
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
Labels: Minor, Fix, Stability

#1120 [GEN][ZH] Remove unnecessary NULL pointer tests in UpdateSlotList()
  Generals/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp
  Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GUIUtil.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/GameInfo.cpp
Labels: Minor, Refactor

#1121 [GEN][ZH] Prevent dereferencing NULL pointer 'button' in ScriptActions::doCameoFlash()
  Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptActions.cpp
Labels: Minor, Fix, Stability

#1123 [GEN][ZH] Prevent using uninitialized memory 'hr' in W3DShaderManager::LoadAndCreateD3DShader()
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp
Labels: Minor, Refactor

#1125 [GEN][ZH] Add missing break keywords between switch labels in W3DProjectedShadow, W3DDisplay, W3DWater
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp
Labels: Minor, Refactor

#1126 [GEN][ZH] Fix dereferencing NULL pointer 'CBScheme->m_buttonQueueImage' in ControlBarSchemeManager::preloadAssets()
  Generals/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ControlBar/ControlBarScheme.cpp
Labels: Minor, Fix

#1127 [GEN][ZH] Fix using uninitialized memory 'window' in createGadget()
  Generals/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GameWindowManagerScript.cpp
Labels: Minor, Fix

#1093 [GEN][ZH] Fix dereferencing NULL pointer 'victimObj' in WeaponTemplate::estimateWeaponTemplateDamage()
  Generals/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp
Labels: Minor, Refactor

#923 [GEN][ZH] Add Replay Simulation feature
  Core/GameEngine/CMakeLists.txt
  Core/GameEngine/Include/Common/ReplaySimulation.h
  Core/GameEngine/Include/Common/WorkerProcess.h
  Core/GameEngine/Source/Common/ReplaySimulation.cpp
  Core/GameEngine/Source/Common/WorkerProcess.cpp
  Dependencies/Utility/Utility/CppMacros.h
  Generals/Code/GameEngine/CMakeLists.txt
  Generals/Code/GameEngine/Include/Common/GameEngine.h
  Generals/Code/GameEngine/Include/Common/GlobalData.h
  Generals/Code/GameEngine/Include/Common/Recorder.h
  Generals/Code/GameEngine/Include/GameClient/ClientInstance.h
  Generals/Code/GameEngine/Include/GameClient/GameClient.h
  Generals/Code/GameEngine/Source/Common/CommandLine.cpp
  Generals/Code/GameEngine/Source/Common/GameEngine.cpp
  Generals/Code/GameEngine/Source/Common/GameMain.cpp
  Generals/Code/GameEngine/Source/Common/GlobalData.cpp
  Generals/Code/GameEngine/Source/Common/Recorder.cpp
  Generals/Code/GameEngine/Source/Common/System/Debug.cpp
  Generals/Code/GameEngine/Source/GameClient/ClientInstance.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
  Generals/Code/GameEngine/Source/GameClient/GameClient.cpp
  Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
  Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
  Generals/Code/GameEngine/Source/GameNetwork/IPEnumeration.cpp
  Generals/Code/Libraries/Source/WWVegas/WW3D2/textureloader.cpp
  Generals/Code/Main/WinMain.cpp
  GeneralsMD/Code/GameEngine/CMakeLists.txt
  GeneralsMD/Code/GameEngine/Include/Common/GameEngine.h
  GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
  GeneralsMD/Code/GameEngine/Include/Common/Recorder.h
  GeneralsMD/Code/GameEngine/Include/GameClient/ClientInstance.h
  GeneralsMD/Code/GameEngine/Include/GameClient/GameClient.h
  GeneralsMD/Code/GameEngine/Source/Common/CommandLine.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GameMain.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp
  GeneralsMD/Code/GameEngine/Source/Common/System/Debug.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/ClientInstance.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ScoreScreen.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GameClient.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp
  GeneralsMD/Code/GameEngine/Source/GameNetwork/IPEnumeration.cpp
  GeneralsMD/Code/Main/WinMain.cpp
Labels: Enhancement, Major, Gen, ZH, Debug

#1100 [ZH] Prevent dereferencing NULL pointer 'state' in StateMachine::xfer()
  GeneralsMD/Code/GameEngine/Source/Common/StateMachine.cpp
Labels: Minor, Fix

#1110 [GEN][ZH] Remove unnecessary NULL pointer test in CrateCollide::isValidToExecute()
  Generals/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/CrateCollide.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Collide/CrateCollide/CrateCollide.cpp
Labels: Minor, Refactor

#1124 [GEN][ZH] Prevent dereferencing NULL pointer 'pbmi' and memory leaks in CreateBMPFile()
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Labels: Minor, Memory, Fix

#1130 [GEN][ZH] Do not acquire money transaction audio if the play sound parameter is false
  Generals/Code/GameEngine/Source/Common/RTS/Money.cpp
  GeneralsMD/Code/GameEngine/Source/Common/RTS/Money.cpp
Labels: Minor, Refactor

#1131 [GEN][ZH] Prevent using uninitialized memory 'delta' in Dict::ensureUnique()
  Generals/Code/GameEngine/Source/Common/Dict.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Dict.cpp
Labels: Minor, Fix

#1133 [GEN][ZH] Prevent using uninitialized memory 'result' in PartitionData::calcMaxCoiForShape()
  Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
Labels: Minor, Refactor

#1135 [GEN][ZH] Fix GEOMETRY_SPHERE & GEOMETRY_CYLINDER treated as GEOMETRY_BOX in PartitionData::calcMaxCoiForShape()
  Generals/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/PartitionManager.cpp
Labels: Minor, Fix

#1136 [GEN][ZH] Remove unnecessary NULL pointer test in SaveLoadMenuSystem()
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupSaveLoad.cpp
Labels: Minor, Refactor

#1139 [GEN][ZH] Suppress compile warning about buffer overrun while writing to 'm_structuresToRepair' in AIPlayer::repairStructure()
  Generals/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIPlayer.cpp
Labels: Minor, Refactor

#1140 [GEN][ZH] Prevent dereferencing NULL pointer 'damageSource' in TransitionDamageFX::onBodyDamageStateChange()
  Generals/Code/GameEngine/Source/GameLogic/Object/Damage/TransitionDamageFX.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Damage/TransitionDamageFX.cpp
Labels: Minor, Refactor

#1142 [GEN][ZH] Prevent dereferencing NULL pointer 'drawable' in BoneFXUpdate::resolveBoneLocations()
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BoneFXUpdate.cpp
Labels: Minor, Fix

#1144 [CORE] Prevent using uninitialized memory 'listline' in Cftp::FindFile()
  Core/Libraries/Source/WWVegas/WWDownload/FTP.CPP
Labels: Minor, Fix

#1145 [CORE] Prevent using uninitialized memory 'name' in RenderObjPersistFactoryClass::Load()
  Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp
Labels: Minor, Fix

#1146 [GEN][ZH] Remove unnecessary NULL pointer test in RTS3DScene::Visibility_Check()
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
Labels: Minor, Refactor

#1150 [GEN][ZH] Prevent reading invalid data from 'm_numLevelPresets' in GameLODManager::newLODPreset()
  Generals/Code/GameEngine/Source/Common/GameLOD.cpp
  GeneralsMD/Code/GameEngine/Source/Common/GameLOD.cpp
Labels: Minor, Refactor

#1141 [GEN][ZH] Prevent dereferencing NULL pointer 'theTemplate' in UpgradeMuxData::getUpgradeActivationMasks()
  Generals/Code/GameEngine/Source/Common/Thing/Module.cpp
  GeneralsMD/Code/GameEngine/Source/Common/Thing/Module.cpp
Labels: Minor, Fix

#1184 [GEN][ZH] Fix World Builder crashing on drawing scene, introduced by previous change #1146
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp
Labels: Blocker, WorldBuilder, ThisProject, Crash

#1117 [GEN][ZH] Check vector size before accessing first element in World Builder's MapObjectProps and ScorchOptions
  Generals/Code/Tools/WorldBuilder/include/ScorchOptions.h
  Generals/Code/Tools/WorldBuilder/include/mapobjectprops.h
  Generals/Code/Tools/WorldBuilder/src/ScorchOptions.cpp
  Generals/Code/Tools/WorldBuilder/src/mapobjectprops.cpp
  GeneralsMD/Code/Tools/WorldBuilder/include/ScorchOptions.h
  GeneralsMD/Code/Tools/WorldBuilder/include/mapobjectprops.h
  GeneralsMD/Code/Tools/WorldBuilder/src/ScorchOptions.cpp
  GeneralsMD/Code/Tools/WorldBuilder/src/mapobjectprops.cpp
Labels: Bug, Minor, WorldBuilder

#1148 [GEN][ZH] Prevent dereferencing NULL pointer 'TheControlBar', 'window' in ControlBarCallback
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/ControlBarCallback.cpp
Labels: Minor, Refactor

#1156 [GEN][ZH] Fix missing unit voice when attacking the ground
  Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp
Labels: Audio, Bug, Minor

#1159 [GEN][ZH] Fix missing break at switch case GEM_UPDATE_TEXT in PopupReplaySystem()
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/PopupReplay.cpp
Labels: Minor, Fix

#1162 [GEN][ZH] Fix missing break at switch case PeerResponse::PEERRESPONSE_DISCONNECT in WOLGameSetupMenuUpdate(), WOLLobbyMenuUpdate()
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLGameSetupMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/WOLLobbyMenu.cpp
Labels: Minor, Fix

#1165 [GEN][ZH] Fix wrong returned name for D3DTSS_TEXTURETRANSFORMFLAGS in DX8Wrapper::Get_DX8_Texture_Stage_State_Value_Name()
  Generals/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
  GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/dx8wrapper.cpp
Labels: Minor, Debug, Fix

#1036 [CMAKE] Remove obsolete interface libraries, add missing core gameengine include interface library
  Core/CMakeLists.txt
  Generals/Code/CMakeLists.txt
  Generals/Code/Tools/WorldBuilder/CMakeLists.txt
  GeneralsMD/Code/CMakeLists.txt
  GeneralsMD/Code/Tools/WorldBuilder/CMakeLists.txt
Labels: Minor, Build

#1195 [CORE] Fix memset zero in max2w3d's VectorChannelClass::SaveAdaptiveDelta()
  Core/Tools/WW3D/max2w3d/vchannel.cpp
Labels: Minor, Tools, Fix

#759 [GEN][ZH] Fix Retail Mismatch in Release Build when Logging is enabled
  Generals/Code/GameEngine/Source/GameLogic/AI/AISkirmishPlayer.cpp
  Generals/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
  Generals/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AISkirmishPlayer.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/PhysicsUpdate.cpp
Labels: Minor, Gen, ZH, Debug, Fix

#1197 [GEN][ZH] Fix untimely Exe CRC generation in GlobalData
  Generals/Code/GameEngine/Include/Common/GlobalData.h
  Generals/Code/GameEngine/Source/Common/GlobalData.cpp
  GeneralsMD/Code/GameEngine/Include/Common/GlobalData.h
  GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp
Labels: Bug, Major, ThisProject

#1092 [GEN][ZH] Remove unnecessary NULL pointer tests in InGameUI
  Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp
Labels: Minor, Refactor

#1206 [ZH] Fix crash with USA Particle Cannon when the last scripted target waypoint is reached before the end of the firing sequence
  GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/ParticleUplinkCannonUpdate.cpp
Labels: Bug, Major, USA, ZH, Crash, Mod

#1208 [GEN][ZH] Prevent duplicate replays from being shown in the Replay Menu
  Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
  GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp
Labels: Bug, GUI, Minor, Gen, ZH

#1152 [ZH] Fix compiler warning about incorrect order of operations in WorldHeightMap::getPointerToTileData()
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/WorldHeightMap.cpp
Labels: Minor, Refactor

#1200 [GEN][ZH] Fix game crash in AIGroup::groupSell()
  Generals/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
  GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIGroup.cpp
Labels: Major, Gen, ZH, Crash

#460 [GEN][ZH] Enable resolutions with aspect ratios different from 4:3 in Options Menu
  Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
  GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp
Labels: Design, Enhancement, GUI, Major, Gen, ZH
